# Generated by Django 5.2.16 on 2026-07-09 11:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actor", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="actor",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="actor",
            name="birth_date",
        ),
        migrations.RemoveField(
            model_name="actor",
            name="image_url",
        ),
        migrations.AddField(
            model_name="actor",
            name="age",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(120),
                ],
            ),
        ),
        migrations.AddField(
            model_name="actor",
            name="photo_url",
            field=models.URLField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="actor",
            name="name",
            field=models.CharField(
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        message="you can only use letters..",
                        regex="^[a-zA-ZçÇğĞıİöÖşŞüÜ\\s]+$",
                    )
                ],
            ),
        ),
    ]
