# Generated by Django 5.2.16 on 2026-07-08 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("directors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("genre", models.CharField(max_length=100)),
                ("rating", models.FloatField(default=0.0)),
                (
                    "poster_url",
                    models.URLField(
                        blank=True,
                        default="https://via.placeholder.com/300x450",
                        null=True,
                    ),
                ),
                ("release_date", models.DateField(blank=True, null=True)),
                (
                    "director",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movies",
                        to="directors.director",
                    ),
                ),
            ],
        ),
    ]
