# Generated by Django 5.2.16 on 2026-07-08 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="description",
            new_name="comment",
        ),
    ]
