# Generated by Django 5.2.16 on 2026-07-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_rename_description_movie_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="trailer_url",
            field=models.URLField(
                blank=True,
                help_text="YouTube Embed URL (örn: https://www.youtube.com/embed/...)",
                max_length=500,
                null=True,
            ),
        ),
    ]
