# Generated by Django 5.2.16 on 2026-07-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_movie_trailer_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="trailer_url",
            field=models.URLField(
                blank=True,
                help_text="YouTube Embed URL (ex: https://www.youtube.com/embed/...)",
                max_length=500,
                null=True,
            ),
        ),
    ]
