# Generated by Django 5.2.16 on 2026-07-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actor", "0002_remove_actor_bio_remove_actor_birth_date_and_more"),
        ("movies", "0004_alter_movie_trailer_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="actor",
            field=models.ManyToManyField(
                blank=True, related_name="movies", to="actor.actor"
            ),
        ),
    ]
